# Using PyTorch to Generate Spongebob Transcripts

1. import libraries we will depend on.

In [1]:
import os
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from collections import Counter
from argparse import Namespace

2. Set variables for this project

In [2]:
flags = Namespace(
    train_file='../web_scraper/spongebob-transcript.txt',
    seq_size=32,
    batch_size=16,
    embedding_size=64,
    lstm_size=64,
    gradients_norm=5,
    initial_words=['_________________________________________________________'],
    predict_top_k=5,
    checkpoint_path='checkpoint'
)

3. Define a function to process the raw data

In [3]:
def process_data_from_file(train_file, batch_size, seq_size):
    with open(train_file, 'r') as file:
        text = file.read()
    text = text.split()
    
    word_counts = Counter(text)
    
    sorted_vocab = sorted(word_counts, key=word_counts.get, reverse=True)
    int_to_vocab = {k: w for k, w in enumerate(sorted_vocab)}
    vocab_to_int = {w: k for k, w in int_to_vocab.items()}
    n_vocab = len(int_to_vocab)
    
    int_text = [vocab_to_int[w] for w in text]
    num_batches = int(len(int_text) / (seq_size * batch_size))
    in_text = int_text[:num_batches * batch_size * seq_size]
    out_text = np.zeros_like(in_text)
    out_text[:-1] = in_text[1:]
    out_text[-1] = in_text[0]
    in_text = np.reshape(in_text, (batch_size, -1))
    out_text = np.reshape(out_text, (batch_size, -1))
    
    return int_to_vocab, vocab_to_int, n_vocab, in_text, out_text

#Call the function and set some variables
device = torch.device('cpu')
int_to_vocab, vocab_to_int, n_vocab, in_text, out_text = process_data_from_file(flags.train_file, flags.batch_size, flags.seq_size)

4. Take a look at some of the data

In [4]:
print('Vocabulary size:\n', n_vocab)
print('Out Text Matrix:\n', out_text)

Vocabulary size:
 71566
Out Text Matrix:
 [[12942   265 23161 ...   543   227    72]
 [  647    82   196 ...     1    89    30]
 [    8     3  4628 ...   188    70 15392]
 ...
 [ 2404    22    76 ... 11386    29  8081]
 [ 1060   131     0 ...  4740     5 14194]
 [ 7903  4002   203 ...   182   626  2083]]


Looks good. Now let's:
5. Create the network in Pytorch

In [5]:
class RNNModule(nn.Module):
    #define necessary layers in the constructor:
    #embedding layer, LSTM layer, dense layer
    def __init__(self, n_vocab, seq_size, embedding_size, lstm_size):
        super(RNNModule, self).__init__()
        self.seq_size = seq_size
        self.lstm_size = lstm_size
        self.embedding = nn.Embedding(n_vocab, embedding_size)
        self.lstm = nn.LSTM(embedding_size, lstm_size, batch_first=True)
        self.dense = nn.Linear(lstm_size, n_vocab)
    
    #define function for forward pass
    def forward(self, x, prev_state):
        embed = self.embedding(x)
        output, state = self.lstm(embed, prev_state)
        logits = self.dense(output)
        return logits, state
    
    #define function to reset state at each epoch
    def zero_state(self, batch_size):
        return (torch.zeros(1, batch_size, self.lstm_size),
                torch.zeros(1, batch_size, self.lstm_size))

#Instantiate the network
net = RNNModule(n_vocab, flags.seq_size, flags.embedding_size, flags.lstm_size)
net = net.to(device)

6. Define a function to handle loss and training

In [6]:
def get_loss_and_train_op(net, lr=0.001):
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(net.parameters(), lr=lr)
    return criterion, optimizer

#Call the function
criterion, optimizer = get_loss_and_train_op(net, 0.01)

7. Define the function to get batches for training

In [7]:
def get_batches(in_text, out_text, batch_size, seq_size):
    num_batches = np.prod(in_text.shape) // (seq_size * batch_size)
    for i in range(0, num_batches * seq_size, seq_size):
        yield in_text[:, i:i+seq_size], out_text[:, i:i+seq_size]

8. Define the prediction function which will be used in training

In [8]:
def predict(device, net, words, n_vocab, vocab_to_int, int_to_vocab, top_k=5):
    # tells the network we are about to evaluate
    net.eval()
    
    state_h, state_c = net.zero_state(1)
    state_h = state_h.to(device)
    state_c = state_c.to(device)
    for w in words:
        ix = torch.tensor([[vocab_to_int[w]]]).to(device)
        output, (state_h, state_c) = net(ix, (state_h, state_c))
    
    _, top_ix = torch.topk(output[0], k=top_k)
    choices = top_ix.tolist()
    choice = np.random.choice(choices[0])
    
    # append another word
    words.append(int_to_vocab[choice])
    
    # append 100 more
    for _ in range(100):
        ix = torch.tensor([[choice]]).to(device)
        output, (state_h, state_c) = net(ix, (state_h, state_c))
        
        _, top_ix = torch.topk(output[0], k=top_k)
        choices = top_ix.tolist()
        choice = np.random.choice(choices[0])
        words.append(int_to_vocab[choice])
    
    print(' '.join(words))
    

8. Training! Loop through batches for each epoch, compute losses and update network parameters

In [ ]:
iteration = 0
for e in range(50):
    print('Epoch: ', e)
    batches = get_batches(in_text, out_text, flags.batch_size, flags.seq_size)
    state_h, state_c = net.zero_state(flags.batch_size)
    
    state_h = state_h.to(device)
    state_c = state_c.to(device)
    for x, y in batches:
        iteration += 1
        print('Iteration: ', iteration)
        
        # train
        net.train()
        
        # reset gradients
        optimizer.zero_grad()
        
        x = torch.tensor(x).to(device)
        y = torch.tensor(y).to(device)
            
        logits, (state_h, state_c) = net(x, (state_h, state_c))
        loss = criterion(logits.transpose(1,2), y)
        
        # detach() so pytorch can calculate loss
        state_h = state_h.detach()
        state_c = state_c.detach()
        
        loss_value = loss.item()
        
        # back propagation
        loss.backward()
        
        # gradient clipping 
        _ = torch.nn.utils.clip_grad_norm_(net.parameters(), flags.gradients_norm)
        
        # update network parameters
        optimizer.step()
        
        # print loss values to the console during training
        if iteration % 100 == 0:
            print('Epoch: {}/{}'.format(e, 200),
                  'Iteration: {}'.format(iteration),
                  'Loss: {}'.format(loss_value))
        
        # print a little sample of text during training
        if iteration % 1000 == 0:
            predict(device, net, flags.initial_words, n_vocab, vocab_to_int, int_to_vocab, top_k=5)
            torch.save(net.state_dict(), '../checkpoint_pt/model-{}-{}.pth'.format(iteration, loss_value))

Epoch:  0
Iteration:  1
Iteration:  2
Iteration:  3
Iteration:  4
Iteration:  5
Iteration:  6
Iteration:  7
Iteration:  8
Iteration:  9
Iteration:  10
Iteration:  11
Iteration:  12
Iteration:  13
Iteration:  14
Iteration:  15
Iteration:  16
Iteration:  17
Iteration:  18
Iteration:  19
Iteration:  20
Iteration:  21
Iteration:  22
Iteration:  23
Iteration:  24
Iteration:  25
Iteration:  26
Iteration:  27
Iteration:  28
Iteration:  29
Iteration:  30
Iteration:  31
Iteration:  32
Iteration:  33
Iteration:  34
Iteration:  35
Iteration:  36
Iteration:  37
Iteration:  38
Iteration:  39
Iteration:  40
Iteration:  41
Iteration:  42
Iteration:  43
Iteration:  44
Iteration:  45
Iteration:  46
Iteration:  47
Iteration:  48
Iteration:  49
Iteration:  50
Iteration:  51
Iteration:  52
Iteration:  53
Iteration:  54
Iteration:  55
Iteration:  56
Iteration:  57
Iteration:  58
Iteration:  59
Iteration:  60
Iteration:  61
Iteration:  62
Iteration:  63
Iteration:  64
Iteration:  65
Iteration:  66
Iteration

Iteration:  503
Iteration:  504
Iteration:  505
Iteration:  506
Iteration:  507
Iteration:  508
Iteration:  509
Iteration:  510
Iteration:  511
Iteration:  512
Iteration:  513
Iteration:  514
Iteration:  515
Iteration:  516
Iteration:  517
Iteration:  518
Iteration:  519
Iteration:  520
Iteration:  521
Iteration:  522
Iteration:  523
Iteration:  524
Iteration:  525
Iteration:  526
Iteration:  527
Iteration:  528
Iteration:  529
Iteration:  530
Iteration:  531
Iteration:  532
Iteration:  533
Iteration:  534
Iteration:  535
Iteration:  536
Iteration:  537
Iteration:  538
Iteration:  539
Iteration:  540
Iteration:  541
Iteration:  542
Iteration:  543
Iteration:  544
Iteration:  545
Iteration:  546
Iteration:  547
Iteration:  548
Iteration:  549
Iteration:  550
Iteration:  551
Iteration:  552
Iteration:  553
Iteration:  554
Iteration:  555
Iteration:  556
Iteration:  557
Iteration:  558
Iteration:  559
Iteration:  560
Iteration:  561
Iteration:  562
Iteration:  563
Iteration:  564
Iteratio

_________________________________________________________ ha! I got an idea. Squidward: I have an idea and I don't want you to be my friend, I'm gonna do that. Squidward: I need to be a new Krabby Patties on my old idea! Squidward: Hey, that's a good time for your thumbs I got you for you and I can't be my old little clown. I don't know you have to be a good thing to go in the door is a little ice cream is in my new best friend I got a little idea! Mr. Krabs: Oh, that's you have a good to get to get
Iteration:  1001
Iteration:  1002
Iteration:  1003
Iteration:  1004
Iteration:  1005
Iteration:  1006
Iteration:  1007
Iteration:  1008
Iteration:  1009
Iteration:  1010
Iteration:  1011
Iteration:  1012
Iteration:  1013
Iteration:  1014
Iteration:  1015
Iteration:  1016
Iteration:  1017
Iteration:  1018
Iteration:  1019
Iteration:  1020
Iteration:  1021
Iteration:  1022
Iteration:  1023
Iteration:  1024
Iteration:  1025
Iteration:  1026
Iteration:  1027
Iteration:  1028
Iteration:  1029
It

Iteration:  1441
Iteration:  1442
Iteration:  1443
Iteration:  1444
Iteration:  1445
Iteration:  1446
Iteration:  1447
Iteration:  1448
Iteration:  1449
Iteration:  1450
Iteration:  1451
Iteration:  1452
Iteration:  1453
Iteration:  1454
Iteration:  1455
Iteration:  1456
Iteration:  1457
Iteration:  1458
Iteration:  1459
Iteration:  1460
Iteration:  1461
Iteration:  1462
Iteration:  1463
Iteration:  1464
Iteration:  1465
Iteration:  1466
Iteration:  1467
Iteration:  1468
Iteration:  1469
Iteration:  1470
Iteration:  1471
Iteration:  1472
Iteration:  1473
Iteration:  1474
Iteration:  1475
Iteration:  1476
Iteration:  1477
Iteration:  1478
Iteration:  1479
Iteration:  1480
Iteration:  1481
Iteration:  1482
Iteration:  1483
Iteration:  1484
Iteration:  1485
Iteration:  1486
Iteration:  1487
Iteration:  1488
Iteration:  1489
Iteration:  1490
Iteration:  1491
Iteration:  1492
Iteration:  1493
Iteration:  1494
Iteration:  1495
Iteration:  1496
Iteration:  1497
Iteration:  1498
Iteration:  14

Iteration:  1908
Iteration:  1909
Iteration:  1910
Iteration:  1911
Iteration:  1912
Iteration:  1913
Iteration:  1914
Iteration:  1915
Iteration:  1916
Iteration:  1917
Iteration:  1918
Iteration:  1919
Iteration:  1920
Iteration:  1921
Iteration:  1922
Iteration:  1923
Iteration:  1924
Iteration:  1925
Iteration:  1926
Iteration:  1927
Iteration:  1928
Iteration:  1929
Iteration:  1930
Iteration:  1931
Iteration:  1932
Iteration:  1933
Iteration:  1934
Iteration:  1935
Iteration:  1936
Iteration:  1937
Iteration:  1938
Iteration:  1939
Iteration:  1940
Iteration:  1941
Iteration:  1942
Iteration:  1943
Iteration:  1944
Iteration:  1945
Iteration:  1946
Iteration:  1947
Iteration:  1948
Iteration:  1949
Iteration:  1950
Iteration:  1951
Iteration:  1952
Iteration:  1953
Iteration:  1954
Iteration:  1955
Iteration:  1956
Iteration:  1957
Iteration:  1958
Iteration:  1959
Iteration:  1960
Iteration:  1961
Iteration:  1962
Iteration:  1963
Iteration:  1964
Iteration:  1965
Iteration:  19

Iteration:  2318
Iteration:  2319
Iteration:  2320
Iteration:  2321
Iteration:  2322
Iteration:  2323
Iteration:  2324
Iteration:  2325
Iteration:  2326
Iteration:  2327
Iteration:  2328
Iteration:  2329
Iteration:  2330
Iteration:  2331
Iteration:  2332
Iteration:  2333
Iteration:  2334
Iteration:  2335
Iteration:  2336
Iteration:  2337
Iteration:  2338
Iteration:  2339
Iteration:  2340
Iteration:  2341
Iteration:  2342
Iteration:  2343
Iteration:  2344
Iteration:  2345
Iteration:  2346
Iteration:  2347
Iteration:  2348
Iteration:  2349
Iteration:  2350
Iteration:  2351
Iteration:  2352
Iteration:  2353
Iteration:  2354
Iteration:  2355
Iteration:  2356
Iteration:  2357
Iteration:  2358
Iteration:  2359
Iteration:  2360
Iteration:  2361
Iteration:  2362
Iteration:  2363
Iteration:  2364
Iteration:  2365
Iteration:  2366
Iteration:  2367
Iteration:  2368
Iteration:  2369
Iteration:  2370
Iteration:  2371
Iteration:  2372
Iteration:  2373
Iteration:  2374
Iteration:  2375
Iteration:  23

Iteration:  2788
Iteration:  2789
Iteration:  2790
Iteration:  2791
Iteration:  2792
Iteration:  2793
Iteration:  2794
Iteration:  2795
Iteration:  2796
Iteration:  2797
Iteration:  2798
Iteration:  2799
Iteration:  2800
Epoch: 1/200 Iteration: 2800 Loss: 5.912009239196777
Iteration:  2801
Iteration:  2802
Iteration:  2803
Iteration:  2804
Iteration:  2805
Iteration:  2806
Iteration:  2807
Iteration:  2808
Iteration:  2809
Iteration:  2810
Iteration:  2811
Iteration:  2812
Iteration:  2813
Iteration:  2814
Iteration:  2815
Iteration:  2816
Iteration:  2817
Iteration:  2818
Iteration:  2819
Iteration:  2820
Iteration:  2821
Iteration:  2822
Iteration:  2823
Iteration:  2824
Iteration:  2825
Iteration:  2826
Iteration:  2827
Iteration:  2828
Iteration:  2829
Iteration:  2830
Iteration:  2831
Iteration:  2832
Iteration:  2833
Iteration:  2834
Iteration:  2835
Iteration:  2836
Iteration:  2837
Iteration:  2838
Iteration:  2839
Iteration:  2840
Iteration:  2841
Iteration:  2842
Iteration:  

Iteration:  3169
Iteration:  3170
Iteration:  3171
Iteration:  3172
Iteration:  3173
Iteration:  3174
Iteration:  3175
Iteration:  3176
Iteration:  3177
Iteration:  3178
Iteration:  3179
Iteration:  3180
Iteration:  3181
Iteration:  3182
Iteration:  3183
Iteration:  3184
Iteration:  3185
Iteration:  3186
Iteration:  3187
Iteration:  3188
Iteration:  3189
Iteration:  3190
Iteration:  3191
Iteration:  3192
Iteration:  3193
Iteration:  3194
Iteration:  3195
Iteration:  3196
Iteration:  3197
Iteration:  3198
Iteration:  3199
Iteration:  3200
Epoch: 1/200 Iteration: 3200 Loss: 5.86548376083374
Iteration:  3201
Iteration:  3202
Iteration:  3203
Iteration:  3204
Iteration:  3205
Iteration:  3206
Iteration:  3207
Iteration:  3208
Iteration:  3209
Iteration:  3210
Iteration:  3211
Iteration:  3212
Iteration:  3213
Iteration:  3214
Iteration:  3215
Iteration:  3216
Iteration:  3217
Iteration:  3218
Iteration:  3219
Iteration:  3220
Iteration:  3221
Iteration:  3222
Iteration:  3223
Iteration:  3

Iteration:  3636
Iteration:  3637
Iteration:  3638
Iteration:  3639
Iteration:  3640
Iteration:  3641
Iteration:  3642
Iteration:  3643
Iteration:  3644
Iteration:  3645
Iteration:  3646
Iteration:  3647
Iteration:  3648
Iteration:  3649
Iteration:  3650
Iteration:  3651
Iteration:  3652
Iteration:  3653
Iteration:  3654
Iteration:  3655
Iteration:  3656
Iteration:  3657
Iteration:  3658
Iteration:  3659
Iteration:  3660
Iteration:  3661
Iteration:  3662
Iteration:  3663
Iteration:  3664
Iteration:  3665
Iteration:  3666
Iteration:  3667
Iteration:  3668
Iteration:  3669
Iteration:  3670
Iteration:  3671
Iteration:  3672
Iteration:  3673
Iteration:  3674
Iteration:  3675
Iteration:  3676
Iteration:  3677
Iteration:  3678
Iteration:  3679
Iteration:  3680
Iteration:  3681
Iteration:  3682
Iteration:  3683
Iteration:  3684
Iteration:  3685
Iteration:  3686
Iteration:  3687
Iteration:  3688
Iteration:  3689
Iteration:  3690
Iteration:  3691
Iteration:  3692
Iteration:  3693
Iteration:  36

Iteration:  4002
Iteration:  4003
Iteration:  4004
Iteration:  4005
Iteration:  4006
Iteration:  4007
Iteration:  4008
Iteration:  4009
Iteration:  4010
Iteration:  4011
Iteration:  4012
Iteration:  4013
Iteration:  4014
Iteration:  4015
Iteration:  4016
Iteration:  4017
Iteration:  4018
Iteration:  4019
Iteration:  4020
Iteration:  4021
Iteration:  4022
Iteration:  4023
Iteration:  4024
Iteration:  4025
Iteration:  4026
Iteration:  4027
Iteration:  4028
Iteration:  4029
Iteration:  4030
Iteration:  4031
Iteration:  4032
Iteration:  4033
Iteration:  4034
Iteration:  4035
Iteration:  4036
Iteration:  4037
Iteration:  4038
Iteration:  4039
Iteration:  4040
Iteration:  4041
Iteration:  4042
Iteration:  4043
Iteration:  4044
Iteration:  4045
Iteration:  4046
Iteration:  4047
Iteration:  4048
Iteration:  4049
Iteration:  4050
Iteration:  4051
Iteration:  4052
Iteration:  4053
Iteration:  4054
Iteration:  4055
Iteration:  4056
Iteration:  4057
Iteration:  4058
Iteration:  4059
Iteration:  40

Iteration:  4471
Iteration:  4472
Iteration:  4473
Iteration:  4474
Iteration:  4475
Iteration:  4476
Iteration:  4477
Iteration:  4478
Iteration:  4479
Iteration:  4480
Iteration:  4481
Iteration:  4482
Iteration:  4483
Iteration:  4484
Iteration:  4485
Iteration:  4486
Iteration:  4487
Iteration:  4488
Iteration:  4489
Iteration:  4490
Iteration:  4491
Iteration:  4492
Iteration:  4493
Iteration:  4494
Iteration:  4495
Iteration:  4496
Iteration:  4497
Iteration:  4498
Iteration:  4499
Iteration:  4500
Epoch: 2/200 Iteration: 4500 Loss: 5.124591827392578
Iteration:  4501
Iteration:  4502
Iteration:  4503
Iteration:  4504
Iteration:  4505
Iteration:  4506
Iteration:  4507
Iteration:  4508
Iteration:  4509
Iteration:  4510
Iteration:  4511
Iteration:  4512
Iteration:  4513
Iteration:  4514
Iteration:  4515
Iteration:  4516
Iteration:  4517
Iteration:  4518
Iteration:  4519
Iteration:  4520
Iteration:  4521
Iteration:  4522
Iteration:  4523
Iteration:  4524
Iteration:  4525
Iteration:  

Iteration:  4938
Iteration:  4939
Iteration:  4940
Iteration:  4941
Iteration:  4942
Iteration:  4943
Iteration:  4944
Iteration:  4945
Iteration:  4946
Iteration:  4947
Iteration:  4948
Iteration:  4949
Iteration:  4950
Iteration:  4951
Iteration:  4952
Iteration:  4953
Iteration:  4954
Iteration:  4955
Iteration:  4956
Iteration:  4957
Iteration:  4958
Iteration:  4959
Iteration:  4960
Iteration:  4961
Iteration:  4962
Iteration:  4963
Iteration:  4964
Iteration:  4965
Iteration:  4966
Iteration:  4967
Iteration:  4968
Iteration:  4969
Iteration:  4970
Iteration:  4971
Iteration:  4972
Iteration:  4973
Iteration:  4974
Iteration:  4975
Iteration:  4976
Iteration:  4977
Iteration:  4978
Iteration:  4979
Iteration:  4980
Iteration:  4981
Iteration:  4982
Iteration:  4983
Iteration:  4984
Iteration:  4985
Iteration:  4986
Iteration:  4987
Iteration:  4988
Iteration:  4989
Iteration:  4990
Iteration:  4991
Iteration:  4992
Iteration:  4993
Iteration:  4994
Iteration:  4995
Iteration:  49

Iteration:  5263
Iteration:  5264
Iteration:  5265
Iteration:  5266
Iteration:  5267
Iteration:  5268
Iteration:  5269
Iteration:  5270
Iteration:  5271
Iteration:  5272
Iteration:  5273
Iteration:  5274
Iteration:  5275
Iteration:  5276
Iteration:  5277
Iteration:  5278
Iteration:  5279
Iteration:  5280
Iteration:  5281
Iteration:  5282
Iteration:  5283
Iteration:  5284
Iteration:  5285
Iteration:  5286
Iteration:  5287
Iteration:  5288
Iteration:  5289
Iteration:  5290
Iteration:  5291
Iteration:  5292
Iteration:  5293
Iteration:  5294
Iteration:  5295
Iteration:  5296
Iteration:  5297
Iteration:  5298
Iteration:  5299
Iteration:  5300
Epoch: 2/200 Iteration: 5300 Loss: 5.309352874755859
Iteration:  5301
Iteration:  5302
Iteration:  5303
Iteration:  5304
Iteration:  5305
Iteration:  5306
Iteration:  5307
Iteration:  5308
Iteration:  5309
Iteration:  5310
Iteration:  5311
Iteration:  5312
Iteration:  5313
Iteration:  5314
Iteration:  5315
Iteration:  5316
Iteration:  5317
Iteration:  

Iteration:  5730
Iteration:  5731
Iteration:  5732
Iteration:  5733
Iteration:  5734
Iteration:  5735
Iteration:  5736
Iteration:  5737
Iteration:  5738
Iteration:  5739
Iteration:  5740
Iteration:  5741
Iteration:  5742
Iteration:  5743
Iteration:  5744
Iteration:  5745
Iteration:  5746
Iteration:  5747
Iteration:  5748
Iteration:  5749
Iteration:  5750
Iteration:  5751
Iteration:  5752
Iteration:  5753
Iteration:  5754
Iteration:  5755
Iteration:  5756
Iteration:  5757
Iteration:  5758
Iteration:  5759
Iteration:  5760
Iteration:  5761
Iteration:  5762
Iteration:  5763
Iteration:  5764
Iteration:  5765
Iteration:  5766
Iteration:  5767
Iteration:  5768
Iteration:  5769
Iteration:  5770
Iteration:  5771
Iteration:  5772
Iteration:  5773
Iteration:  5774
Iteration:  5775
Iteration:  5776
Iteration:  5777
Iteration:  5778
Iteration:  5779
Iteration:  5780
Iteration:  5781
Iteration:  5782
Iteration:  5783
Iteration:  5784
Iteration:  5785
Iteration:  5786
Iteration:  5787
Iteration:  57

Iteration:  6023
Iteration:  6024
Iteration:  6025
Iteration:  6026
Iteration:  6027
Iteration:  6028
Iteration:  6029
Iteration:  6030
Iteration:  6031
Iteration:  6032
Iteration:  6033
Iteration:  6034
Iteration:  6035
Iteration:  6036
Iteration:  6037
Iteration:  6038
Iteration:  6039
Iteration:  6040
Iteration:  6041
Iteration:  6042
Iteration:  6043
Iteration:  6044
Iteration:  6045
Iteration:  6046
Iteration:  6047
Iteration:  6048
Iteration:  6049
Iteration:  6050
Iteration:  6051
Iteration:  6052
Iteration:  6053
Iteration:  6054
Iteration:  6055
Iteration:  6056
Iteration:  6057
Iteration:  6058
Iteration:  6059
Iteration:  6060
Iteration:  6061
Iteration:  6062
Iteration:  6063
Iteration:  6064
Iteration:  6065
Iteration:  6066
Iteration:  6067
Iteration:  6068
Iteration:  6069
Iteration:  6070
Iteration:  6071
Iteration:  6072
Iteration:  6073
Iteration:  6074
Iteration:  6075
Iteration:  6076
Iteration:  6077
Iteration:  6078
Iteration:  6079
Iteration:  6080
Iteration:  60

Iteration:  6492
Iteration:  6493
Iteration:  6494
Iteration:  6495
Iteration:  6496
Iteration:  6497
Iteration:  6498
Iteration:  6499
Iteration:  6500
Epoch: 3/200 Iteration: 6500 Loss: 4.921543598175049
Iteration:  6501
Iteration:  6502
Iteration:  6503
Iteration:  6504
Iteration:  6505
Iteration:  6506
Iteration:  6507
Iteration:  6508
Iteration:  6509
Iteration:  6510
Iteration:  6511
Iteration:  6512
Iteration:  6513
Iteration:  6514
Iteration:  6515
Iteration:  6516
Iteration:  6517
Iteration:  6518
Iteration:  6519
Iteration:  6520
Iteration:  6521
Iteration:  6522
Iteration:  6523
Iteration:  6524
Iteration:  6525
Iteration:  6526
Iteration:  6527
Iteration:  6528
Iteration:  6529
Iteration:  6530
Iteration:  6531
Iteration:  6532
Iteration:  6533
Iteration:  6534
Iteration:  6535
Iteration:  6536
Iteration:  6537
Iteration:  6538
Iteration:  6539
Iteration:  6540
Iteration:  6541
Iteration:  6542
Iteration:  6543
Iteration:  6544
Iteration:  6545
Iteration:  6546
Iteration:  

Iteration:  6959
Iteration:  6960
Iteration:  6961
Iteration:  6962
Iteration:  6963
Iteration:  6964
Iteration:  6965
Iteration:  6966
Iteration:  6967
Iteration:  6968
Iteration:  6969
Iteration:  6970
Iteration:  6971
Iteration:  6972
Iteration:  6973
Iteration:  6974
Iteration:  6975
Iteration:  6976
Iteration:  6977
Iteration:  6978
Iteration:  6979
Iteration:  6980
Iteration:  6981
Iteration:  6982
Iteration:  6983
Iteration:  6984
Iteration:  6985
Iteration:  6986
Iteration:  6987
Iteration:  6988
Iteration:  6989
Iteration:  6990
Iteration:  6991
Iteration:  6992
Iteration:  6993
Iteration:  6994
Iteration:  6995
Iteration:  6996
Iteration:  6997
Iteration:  6998
Iteration:  6999
Iteration:  7000
Epoch: 3/200 Iteration: 7000 Loss: 4.908538341522217
_________________________________________________________ ha! I got an idea. Squidward: I have an idea and I don't want you to be my friend, I'm gonna do that. Squidward: I need to be a new Krabby Patties on my old idea! Squidward: H

Iteration:  7221
Iteration:  7222
Iteration:  7223
Iteration:  7224
Iteration:  7225
Iteration:  7226
Iteration:  7227
Iteration:  7228
Iteration:  7229
Iteration:  7230
Iteration:  7231
Iteration:  7232
Iteration:  7233
Iteration:  7234
Iteration:  7235
Iteration:  7236
Iteration:  7237
Iteration:  7238
Iteration:  7239
Iteration:  7240
Iteration:  7241
Iteration:  7242
Iteration:  7243
Iteration:  7244
Iteration:  7245
Iteration:  7246
Iteration:  7247
Iteration:  7248
Iteration:  7249
Iteration:  7250
Iteration:  7251
Iteration:  7252
Iteration:  7253
Iteration:  7254
Iteration:  7255
Iteration:  7256
Iteration:  7257
Iteration:  7258
Iteration:  7259
Iteration:  7260
Iteration:  7261
Iteration:  7262
Iteration:  7263
Iteration:  7264
Iteration:  7265
Iteration:  7266
Iteration:  7267
Iteration:  7268
Iteration:  7269
Iteration:  7270
Iteration:  7271
Iteration:  7272
Iteration:  7273
Iteration:  7274
Iteration:  7275
Iteration:  7276
Iteration:  7277
Iteration:  7278
Iteration:  72

Iteration:  7691
Iteration:  7692
Iteration:  7693
Iteration:  7694
Iteration:  7695
Iteration:  7696
Iteration:  7697
Iteration:  7698
Iteration:  7699
Iteration:  7700
Epoch: 3/200 Iteration: 7700 Loss: 4.889597415924072
Iteration:  7701
Iteration:  7702
Iteration:  7703
Iteration:  7704
Iteration:  7705
Iteration:  7706
Iteration:  7707
Iteration:  7708
Iteration:  7709
Iteration:  7710
Iteration:  7711
Iteration:  7712
Iteration:  7713
Iteration:  7714
Iteration:  7715
Iteration:  7716
Iteration:  7717
Iteration:  7718
Iteration:  7719
Iteration:  7720
Iteration:  7721
Iteration:  7722
Iteration:  7723
Iteration:  7724
Iteration:  7725
Iteration:  7726
Iteration:  7727
Iteration:  7728
Iteration:  7729
Iteration:  7730
Iteration:  7731
Iteration:  7732
Iteration:  7733
Iteration:  7734
Iteration:  7735
Iteration:  7736
Iteration:  7737
Iteration:  7738
Iteration:  7739
Iteration:  7740
Iteration:  7741
Iteration:  7742
Iteration:  7743
Iteration:  7744
Iteration:  7745
Iteration:  

Iteration:  8002
Iteration:  8003
Iteration:  8004
Iteration:  8005
Iteration:  8006
Iteration:  8007
Iteration:  8008
Iteration:  8009
Iteration:  8010
Iteration:  8011
Iteration:  8012
Iteration:  8013
Iteration:  8014
Iteration:  8015
Iteration:  8016
Iteration:  8017
Iteration:  8018
Iteration:  8019
Iteration:  8020
Iteration:  8021
Iteration:  8022
Iteration:  8023
Iteration:  8024
Iteration:  8025
Iteration:  8026
Iteration:  8027
Iteration:  8028
Iteration:  8029
Iteration:  8030
Iteration:  8031
Iteration:  8032
Iteration:  8033
Iteration:  8034
Iteration:  8035
Iteration:  8036
Iteration:  8037
Iteration:  8038
Iteration:  8039
Iteration:  8040
Iteration:  8041
Iteration:  8042
Iteration:  8043
Iteration:  8044
Iteration:  8045
Iteration:  8046
Iteration:  8047
Iteration:  8048
Iteration:  8049
Iteration:  8050
Iteration:  8051
Iteration:  8052
Iteration:  8053
Iteration:  8054
Iteration:  8055
Iteration:  8056
Iteration:  8057
Iteration:  8058
Iteration:  8059
Iteration:  80

Iteration:  8472
Iteration:  8473
Iteration:  8474
Iteration:  8475
Iteration:  8476
Iteration:  8477
Iteration:  8478
Iteration:  8479
Iteration:  8480
Iteration:  8481
Iteration:  8482
Iteration:  8483
Iteration:  8484
Iteration:  8485
Iteration:  8486
Iteration:  8487
Iteration:  8488
Iteration:  8489
Iteration:  8490
Iteration:  8491
Iteration:  8492
Iteration:  8493
Iteration:  8494
Iteration:  8495
Iteration:  8496
Iteration:  8497
Iteration:  8498
Iteration:  8499
Iteration:  8500
Epoch: 3/200 Iteration: 8500 Loss: 4.977974891662598
Iteration:  8501
Iteration:  8502
Iteration:  8503
Iteration:  8504
Iteration:  8505
Iteration:  8506
Iteration:  8507
Iteration:  8508
Iteration:  8509
Iteration:  8510
Iteration:  8511
Iteration:  8512
Iteration:  8513
Iteration:  8514
Iteration:  8515
Iteration:  8516
Epoch:  4
Iteration:  8517
Iteration:  8518
Iteration:  8519
Iteration:  8520
Iteration:  8521
Iteration:  8522
Iteration:  8523
Iteration:  8524
Iteration:  8525
Iteration:  8526
It

Iteration:  8938
Iteration:  8939
Iteration:  8940
Iteration:  8941
Iteration:  8942
Iteration:  8943
Iteration:  8944
Iteration:  8945
Iteration:  8946
Iteration:  8947
Iteration:  8948
Iteration:  8949
Iteration:  8950
Iteration:  8951
Iteration:  8952
Iteration:  8953
Iteration:  8954
Iteration:  8955
Iteration:  8956
Iteration:  8957
Iteration:  8958
Iteration:  8959
Iteration:  8960
Iteration:  8961
Iteration:  8962
Iteration:  8963
Iteration:  8964
Iteration:  8965
Iteration:  8966
Iteration:  8967
Iteration:  8968
Iteration:  8969
Iteration:  8970
Iteration:  8971
Iteration:  8972
Iteration:  8973
Iteration:  8974
Iteration:  8975
Iteration:  8976
Iteration:  8977
Iteration:  8978
Iteration:  8979
Iteration:  8980
Iteration:  8981
Iteration:  8982
Iteration:  8983
Iteration:  8984
Iteration:  8985
Iteration:  8986
Iteration:  8987
Iteration:  8988
Iteration:  8989
Iteration:  8990
Iteration:  8991
Iteration:  8992
Iteration:  8993
Iteration:  8994
Iteration:  8995
Iteration:  89

Iteration:  9136
Iteration:  9137
Iteration:  9138
Iteration:  9139
Iteration:  9140
Iteration:  9141
Iteration:  9142
Iteration:  9143
Iteration:  9144
Iteration:  9145
Iteration:  9146
Iteration:  9147
Iteration:  9148
Iteration:  9149
Iteration:  9150
Iteration:  9151
Iteration:  9152
Iteration:  9153
Iteration:  9154
Iteration:  9155
Iteration:  9156
Iteration:  9157
Iteration:  9158
Iteration:  9159
Iteration:  9160
Iteration:  9161
Iteration:  9162
Iteration:  9163
Iteration:  9164
Iteration:  9165
Iteration:  9166
Iteration:  9167
Iteration:  9168
Iteration:  9169
Iteration:  9170
Iteration:  9171
Iteration:  9172
Iteration:  9173
Iteration:  9174
Iteration:  9175
Iteration:  9176
Iteration:  9177
Iteration:  9178
Iteration:  9179
Iteration:  9180
Iteration:  9181
Iteration:  9182
Iteration:  9183
Iteration:  9184
Iteration:  9185
Iteration:  9186
Iteration:  9187
Iteration:  9188
Iteration:  9189
Iteration:  9190
Iteration:  9191
Iteration:  9192
Iteration:  9193
Iteration:  91